# Cleaning Geo-coding Data
The purpose of this notebook/script is to clean the geo-code data points associated with each shooting incident that is documented in Newsroom DB.

In [1]:
import pandas as pd
import numpy as np

In [2]:
#reading .csv file. You can replace shootings_1.csv with any other files that you are interested in analyzing
shootings = pd.read_csv('./shootings_1.csv')

In [3]:
'''
I tend to find that type "date and time" provides programmers with an object oriented accessability
to days, month, and year of a date and time object. That's the main reason why I use it here.
'''
from datetime import datetime
shootings['Date']=shootings['Date'].replace(np.nan,'') #replacing empty NaN values with empty strings
def crap_to_dt(d):
    if(d==''):
        return (d)
    else:
        return (datetime.strptime(str(d) ,'%Y-%m-%d').date()) #converting dates from type string to type date and time
    
shootings['Date']=shootings['Date'].apply(crap_to_dt)
shootings['Date']= pd.to_datetime(shootings['Date'],errors='coerce') #apply pandas date and time function for future indexing

In [4]:
shootings = shootings[shootings['Date'].dt.year>2011] #pulling all the data from 2012 onwards.

In [5]:
geoDF = shootings[['Date','Shooting Location','Geocode Override','Link']]
geoDF.head(3)

,Date,Shooting Location,Geocode Override,Link
60,2012-01-04,"2256 N. Lockwood Avenue, Chicago, IL","(41.922035,-87.758888)",NaN
61,2012-01-05,"3622 W. Lawrence Avenue, Chicago, IL","(41.968612,-87.719245)",NaN
62,2012-01-05,"548 N. Monticello Avenue, Chicago, IL","(41.891433,-87.717758)",NaN

In [6]:
'''
Although this is weird, but empty cells need to be replaced and filled by another value. In this case it's "Foo" (without quotations)
This step is necessary as some entries in the shootings file have no geo-code.
'''
geoDF['Geocode Override']=geoDF['Geocode Override'].replace(np.nan,'FOO')

/Users/Mowafak/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':

In [7]:
geoDF['Geocode Override'].isnull().any() #checking to see if we still have any empty cells?

False

In [8]:
long = []
lat = []

def cleanGeo (geocode):
    if(str(geocode).startswith('(')):
        lat_x,long_y = str(geocode).replace('(','').replace(')','').split(',')
        lat.append(float(lat_x))
        long.append(float(long_y))
    else:
        long.append('')
        lat.append('')
geoDF['Geocode Override'].apply(cleanGeo)

60       None
61       None
62       None
63       None
64       None
65       None
66       None
67       None
68       None
69       None
70       None
71       None
72       None
73       None
74       None
75       None
76       None
77       None
78       None
79       None
80       None
81       None
82       None
83       None
84       None
85       None
86       None
87       None
88       None
89       None
         ...
16589    None
16590    None
16591    None
16592    None
16593    None
16594    None
16595    None
16596    None
16597    None
16598    None
16599    None
16600    None
16601    None
16602    None
16603    None
16604    None
16605    None
16606    None
16607    None
16608    None
16609    None
16610    None
16611    None
16612    None
16613    None
16614    None
16615    None
16616    None
16617    None
16618    None
Name: Geocode Override, dtype: object

In [9]:
'''
Checking if lat and long have the same length. This makes sense, because geo-code data always come in pairs.
'''
print (len(lat))
print (len(long))

16105
16105

In [10]:
'''
adding the cleaned latitude (lat) and longtitude (long) values to a new data frame called geoDF.
'''
geoDF['lat'] = lat
geoDF['long'] = long

/Users/Mowafak/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/Users/Mowafak/anaconda/lib/python3.5/site-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app

In [20]:
geoDF #here's a view of geoDF.

,Date,Shooting Location,Geocode Override,Link,lat,long
60,2012-01-04,"2256 N. Lockwood Avenue, Chicago, IL","(41.922035,-87.758888)",NaN,41.922,-87.7589
61,2012-01-05,"3622 W. Lawrence Avenue, Chicago, IL","(41.968612,-87.719245)",NaN,41.9686,-87.7192
62,2012-01-05,"548 N. Monticello Avenue, Chicago, IL","(41.891433,-87.717758)",NaN,41.8914,-87.7178
63,2012-01-05,"8500 S. Lafayette Avenue, Chicago, IL","(41.7398218810558,-87.6255959272385)",NaN,41.7398,-87.6256
64,2012-01-07,"7100 S. University Avenue, Chicago, IL","(41.76583,-87.597396)",NaN,41.7658,-87.5974
65,2012-01-10,"712 S. Central Park Avenue, Chicago, IL","(41.8722492456436,-87.715652436018)",NaN,41.8722,-87.7157
66,2012-01-10,"1165 N. Milwaukee Avenue, Chicago, IL","(41.901546,-87.663116)",NaN,41.9015,-87.6631
67,2012-01-12,"6135 S. Cottage Grove Avenue, Chicago, IL","(41.7833708971739,-87.605921253562)",NaN,41.7834,-87.6059
68,2012-01-16,"6714 S. Cottage Grove Avenue, Chicago, IL","(41.772567,-87.606155)",NaN,41.7726,-87.6062
69,2012-01-20,"315 W. Chicago Avenue, Chicago, IL","(41.8965272605419,-87.6363495737314)",NaN,41.8965,-87.6363
70,2012-01-20,"1832 W. Juneway Terrace, Chicago, IL","(42.022819,-87.676612)",NaN,42.0228,-87.6766
71,2012-01-21,"6445 S. Kenwood Avenue, Chicago, IL","(41.777408,-87.592544)",NaN,41.7774,-87.5925
72,2012-01-21,"6445 S. Kenwood Avenue, Chicago, IL","(41.777408,-87.592544)",NaN,41.7774,-87.5925
73,2012-01-21,"7259 S. Wolcott Avenue, Chicago, IL","(41.761325,-87.670654)",NaN,41.7613,-87.6707
74,2012-01-27,"2215 S. Spaulding Avenue, Chicago, IL","(41.851234,-87.707313)",NaN,41.8512,-87.7073
75,2012-01-28,"1114 N. Keystone Avenue, Chicago, IL","(41.90134,-87.727821)",NaN,41.9013,-87.7278
76,2012-01-28,"10646 S. Indiana Avenue, Chicago, IL","(41.700536236167,-87.6185142248869)",NaN,41.7005,-87.6185
77,2012-01-31,"3851 W. Jackson Boulevard, Chicago, IL","(41.876861,-87.722648)",NaN,41.8769,-87.7226
78,2012-01-31,"11953 S. Wallace Street, Chicago, IL","(41.6768161207438,-87.6369819045067)",NaN,41.6768,-87.637
79,2012-01-31,"5846 W. Augusta Boulevard, Chicago, IL","(41.8984309583902,-87.772167250514)",NaN,41.8984,-87.7722
80,2012-02-02,"5919 S. Calumet Avenue, Chicago, IL","(41.786876,-87.61692)",NaN,41.7869,-87.6169
81,2012-02-16,"6412 S. Dr. Martin Luther King Jr. Drive, Chic...","(41.778232, -87.61561)",NaN,41.7782,-87.6156
82,2012-02-16,"6412 S. Dr. Martin Luther King Jr. Drive, Chic...","(41.778232, -87.61561)",NaN,41.7782,-87.6156
83,2012-03-01,"2701 W. Jackson Boulevard, Chicago, IL","(41.8774232268333,-87.6939627528191)",NaN,41.8774,-87.694
84,2012-03-02,"803 S. Francisco Avenue, Chicago, IL","(41.8708907067776,-87.6983763277531)",NaN,41.8709,-87.6984
85,2012-03-02,"206 E. 55th Place, Chicago, IL","(41.7938851565123,-87.6205111294985)",NaN,41.7939,-87.6205
86,2012-03-02,"454 E. 95th Street, Chicago, IL","(41.722236,-87.612007)",http://www.chicagotribune.com/news/local/break...,41.7222,-87.612
87,2012-03-03,"5331 W. Congress Parkway, Chicago, IL","(41.873611,-87.758705)",NaN,41.8736,-87.7587
88,2012-03-03,"6832 S. Prairie Avenue, Chicago, IL","(41.770084,-87.619033)",NaN,41.7701,-87.619
89,2012-03-04,"4331 S. Cottage Grove Avenue, Chicago, IL","(41.815872,-87.606231)",NaN,41.8159,-87.6062
...,...,...,...,...,...,...
16589,2017-06-06,"5500 W North Ave, Chicago, IL 60639","(41.9097, -87.76318)",http://www.chicagotribune.com/news/local/break...,41.9097,-87.7632
16590,2017-06-07,"4800 W Gladys Ave, Chicago, IL 60644","(41.8759691759746, -87.745286560199)",http://www.chicagotribune.com/news/local/break...,41.876,-87.7453
16591,2017-06-06,"2900 N Newland Ave, Chicago, IL 60634","(41.9327864013367, -87.7992634170954)",http://www.chicagotribune.com/news/local/break...,41.9328,-87.7993
16592,2017-06-06,"2900 N Newland Ave, Chicago, IL 60634","(41.9327864013367, -87.7992634170954)",http://www.chicagotribune.com/news/local/break...,41.9328,-87.7993
16593,2017-06-07,"1236 S Lawndale Ave, Chicago, IL 60623","(41.86504, -87.71824)",http://www.chicagotribune.com/news/local/break...,41.865,-87.7182
16594,2017-06-07,"1236 S Lawndale Ave, Chicago, IL 60623","(41.86504, -87.71824)",http://www.chicagotribune.com/news/local/break...,41.865,-87.7182
16595,2017-06-07,"500 S Kolmar Ave, Chicago, IL 60624","(41.87406, -87.73974)",http://www.chicagotribune.com/news/local/break...,41.8741,-87.7397
16596,2017-06-07,"1801 E 79th St, Chicago, IL 60649","(41.75128, -87.58084)",http://www.chicagotribune.com/news/local/break...,41.7513,-87.5808
16597,2017-06-07,"1801 E 79th St, Chicago, IL 60649","(41.75128, -87.58084)",http://www.chicagotribune.com/news/local/break...,41.7513,-87.5808
16598,2017-06-07,"1500 N Latrobe Ave, Chicago, IL 60651","(41.90782, -87.75749)",http://www.chicagotribune.com/news/local/break...,41.9078,-87.7575
16599,2017-06-07,"6800 S Damen Ave, Chicago, IL 60636","(41.77012203915, -87.6737268518917)",http://www.chicagotribune.com/news/local/break...,41.7701,-87.6737
16600,2017-06-07,"10500 S Wentworth Ave, Chicago, IL 60628","(41.70331, -87.6285)",http://www.chicagotribune.com/news/local/break...,41.7033,-87.6285
16601,2017-06-07,"1200 S Kedvale Ave, Chicago, IL 60623","(41.86597285359, -87.7288503807519)",http://www.chicagotribune.com/news/local/break...,41.866,-87.7289
16602,2017-06-07,"5400 S Winchester Ave, Chicago, IL 60609","(41.79566, -87.67347)",http://www.chicagotribune.com/news/local/break...,41.7957,-87.6735
16603,2017-06-08,"2800 W 59th St, Chicago, IL 60629","(41.78666, -87.69378)",http://www.chicagotribune.com/news/local/break...,41.7867,-87.6938
16604,2017-06-08,"2800 W 59th St, Chicago, IL 60629","(41.78666, -87.69378)",http://www.chicagotribune.com/news/local/break...,41.7867,-87.6938
16605,2017-06-08,"800 N Pulaski Rd, Chicago, IL 60651","(41.8955359029681, -87.7261252837028)",http://www.chicagotribune.com/news/local/break...,41.8955,-87.7261
16606,2017-06-08,"4100 S Western Ave, Chicago, IL 60609","(41.81915, -87.68512)",http://www.chicagotribune.com/news/local/break...,41.8192,-87.6851
16607,2017-06-07,"900 W 54th St, Chicago, IL 60609","(41.7960349663707, -87.6478339599796)",http://www.chicagotribune.com/news/local/break...,41.796,-87.6478
16608,2017-05-05,"3000 W Jackson Blvd, Chicago, IL 60612","(41.87764, -87.70125)",http://www.chicagotribune.com/news/local/break...,41.8776,-87.7013
16609,2017-05-05,"4801 W Argyle St, Chicago, IL 60630","(41.97141, -87.74803)",http://www.chicagotribune.com/news/local/break...,41.9714,-87.748
16610,2017-05-05,"4527 S Drexel Blvd, Chicago, IL 60653","(41.81233, -87.60364)",http://www.chicagotribune.com/news/local/break...,41.8123,-87.6036
16611,2017-05-06,"6100 S Indiana Ave, Chicago, IL 60637","(41.7836418868993, -87.6206261952396)",http://www.chicagotribune.com/news/local/break...,41.7836,-87.6206
16612,2017-05-06,"4859 S La Crosse Ave, Chicago, IL 60638","(41.80409, -87.74394)",http://www.chicagotribune.com/news/local/break...,41.8041,-87.7439
16613,2017-05-07,"7146 W Diversey Ave, Chicago, IL 60707","(41.93102, -87.8059)",http://www.chicagotribune.com/news/local/break...,41.931,-87.8059
16614,2017-05-07,"2557 W 46th Pl, Chicago, IL 60632","(41.8092313258324, -87.6889581150822)",http://www.chicagotribune.com/news/local/break...,41.8092,-87.689
16615,2017-06-08,"700 E 92nd St, Chicago, IL 60619","(41.7275287614798, -87.6068379822308)",http://www.chicagotribune.com/news/local/break...,41.7275,-87.6068
16616,2017-06-08,"700 E 92nd St, Chicago, IL 60619","(41.7275287614798, -87.6068379822308)",http://www.chicagotribune.com/news/local/break...,41.7275,-87.6068
16617,2017-06-08,"4600 S Troy St, Chicago, IL 60632","(41.80983, -87.70315)",http://www.chicagotribune.com/news/local/break...,41.8098,-87.7031
16618,2017-06-08,"500 N Leamington Ave, Chicago, IL 60644","(41.88944, -87.75452)",http://www.chicagotribune.com/news/local/break...,41.8894,-87.7545

In [21]:
geoDF.to_csv('geoCleaned.csv') #this is to write geoDF to a .csv file.

----------
### Per Kyle Request (06/12/2017)

In [15]:
'''
based on a request from Kyle B., here is the geo-code data for 2017 only.
'''
geoDF_2017 = geoDF[geoDF['Date'].dt.year==2017]
geoDF_2017.to_csv('geoCleaned_2017Only.csv')